post: v1.2.0
rero/rero21.ch pull request #52
Opened 2021-05-12 15:10 UTC by PascalRepond

2021-05-19 08:36 UTC, iGormilhit requested changes

2021-05-19 08:36 UTC, iGormilhit commented on content/post/sortie-de-la-v1.2.0.md
> +Afin d'être ouvert et accessible, RERO ILS se doit également d'être multilingue. Dans cette optique, le logiciel est traduit avec l'aide du service [Weblate](https://hosted.weblate.org/projects/rero_
```suggestion
Afin d'être ouvert et accessible, RERO ILS se doit également d'être multilingue. Dans cette optique, le logiciel est traduit avec l'aide du service [Weblate](https://hosted.weblate.org/projects/rero_plus/rero-ils/) qui permet à l'équipe de développement de collaborer sur ce travail, mais aussi à des personnes externes de participer. En effet, la communauté peut proposer des traductions pour le projet. Nous souhaitons donc remercier les membres suivants pour leurs contributions à ce projet : [Ambros Gattlen](https://hosted.weblate.org/user/ambgat/), [phlostically](https://hosted.weblate.org/user/phlostically/), [Adolfo Jayme Barrientos](https://hosted.weblate.org/user/Fito/), [Allan Nordhøy](https://hosted.weblate.org/user/kingu/). Si vous souhaitez vous aussi apporter votre pierre à l'édifice, n'hésitez pas à visiter [la page du projet sur Weblate](https://hosted.weblate.org/projects/rero_plus/#information).
```
And, yes, I do prefer the bullet point solution. :slightly_smiling_face:

2021-05-19 08:36 UTC, iGormilhit commented on content/post/sortie-de-la-v1.2.0.md
> +## Plusieurs organisations pour un·e lecteur·trice
```suggestion
## Plusieurs organisations pour un lecteur ou une lectrice
```
Si ça te semble envisageable.

2021-05-19 08:36 UTC, iGormilhit commented on content/post/sortie-de-la-v1.2.0.md
> +Parmi les nombreuses nouveautés de la `v1.2.0`, la possibilité pour une usagère ou un usager d'être inscrit dans les bibliothèques de plusieurs organisations était un besoin clair de l'infrastructure
```suggestion
Parmi les nombreuses nouveautés de la `v1.2.0`, pouvoir s'inscrire dans différentes organisations, mais avec le même compte, est un besoin clair de l'infrastructure des bibliothèques de RERO+. 
```

2021-05-19 08:36 UTC, iGormilhit commented on content/post/sortie-de-la-v1.2.0.md
> +Comme nous l'avons déjà [noté](/nouvelle-version-1.1.0/), les données de circulation des utilisatrices et utilisateurs ne sont pas partagées entre différentes organisations ; il est néanmoins probabl
```suggestion
Comme nous l'avons déjà [noté](/nouvelle-version-1.1.0/), les données de circulation des utilisatrices et utilisateurs ne sont pas partagées entre différentes organisations ; il est néanmoins probable que des personnes soient inscrites dans des bibliothèques d'organisations différentes. Celles-ci peuvent désormais consulter leurs données (emprunts, historique, amendes, etc.) des différentes bibliothèques dont elles sont membres grâce à un menu déroulant directement depuis leur compte. Ainsi, il n'est pas nécessaire de changer d'interface ou de se déconnecter pour avoir accès à ces informations. 
```

2021-05-19 09:06 UTC, iGormilhit approved these changes

2021-05-20 05:48 UTC, mmo commented on content/post/sortie-de-la-v1.2.0.en.md
> +After another intense sprint at RERO+ and UCL Louvain, the arrival of version `v1.2.0` brings its share of new features and fixes to stabilize RERO ILS before the *go-live* on July 12th. The complete
```suggestion
After another intense sprint at RERO+ and UCLouvain, the arrival of version `v1.2.0` brings its share of new features and fixes to stabilize RERO ILS before the *go-live* on July 12th. The complete release notes are available on [GitHub](https://github.com/rero/rero-ils/blob/dev/RELEASE-NOTES.rst#v120). This is an opportunity for us to highlight the community aspect of RERO ILS with the system's translation processes.
```

2021-05-20 05:48 UTC, mmo commented on content/post/sortie-de-la-v1.2.0.md
> +Après un nouveau sprint intense chez RERO+ et UCL Louvain, l'arrivée de la version `v1.2.0` amène son lot de nouveautés et de corrections pour stabiliser RERO ILS avant le *go-live* du 12 juillet. Le
```suggestion
Après un nouveau sprint intense chez RERO+ et UCLouvain, l'arrivée de la version `v1.2.0` amène son lot de nouveautés et de corrections pour stabiliser RERO ILS avant le *go-live* du 12 juillet. Les notes de version complètes sont consultables sur [GitHub](https://github.com/rero/rero-ils/blob/dev/RELEASE-NOTES.rst#v120). C'est l'occasion pour nous de mettre en avant l'aspect communautaire de RERO ILS avec les processus de traduction du système.
```

2021-05-20 05:48 UTC, mmo commented on content/post/sortie-de-la-v1.2.0.en.md
> +If you also want to contribute, please visit [the project page on Weblate](https://hosted.weblate.org/projects/rero_plus/#information).
```suggestion
If you would like to contribute as well, please visit [the project page on Weblate](https://hosted.weblate.org/projects/rero_plus/#information).
```

2021-05-20 05:48 UTC, mmo commented on content/post/sortie-de-la-v1.2.0.en.md
> +Among the many new features of `v1.2.0`, the ability for a patron to be registered in the libraries of multiple organizations was a clear need of the RERO+ libraries' infrastructure.
```suggestion
Among the many [new features](https://github.com/rero/rero-ils/blob/dev/RELEASE-NOTES.rst#v120) of `v1.2.0` is the possibility of registering at libraries of multiple organizations using the same account, which is clearly a requirement of patrons of the RERO+ libraries. 
```

2021-05-20 06:13 UTC, pronguen commented on content/post/sortie-de-la-v1.2.0.md
> +Parmi les nombreuses nouveautés de la `v1.2.0`, pouvoir s'inscrire dans différentes organisations, mais avec le même compte, est un besoin clair de l'infrastructure des bibliothèques de RERO+.
Ne pas mettre "utilisateurs" car il apparaît déjà dans la phrase suivante. Par ailleurs, il faudrait le décliner au féminin aussi.

2021-05-20 06:24 UTC, pronguen commented on content/post/sortie-de-la-v1.2.0.en.md
> +As previously [stated](/nouvelle-version-1.1.0/), user traffic data is not
```suggestion
As previously [stated](/nouvelle-version-1.1.0/), user circulation data is not
```

2021-05-20 06:24 UTC, pronguen commented on content/post/sortie-de-la-v1.2.0.en.md
> +are registered in libraries of different organizations. Patrons can now view
On aurait pu rappeler ici par un exemple concret ce que sont différentes organisations... Les gens ne connaissent pas forcément ce terme de jargon RERO ILS.

> it is likely that individuals are registered in libraries of different organizations, for instance once in the RERO Valais network and once in the RBNJ (Neuchâtel-Jura) network.

On aurait aussi pu mettre une note de bas de page l'expliquant:

> An organization in RERO ILS is a group of libraries working closely together, especially by sharing common circulation rules. In RERO+ for instance, all Valais libraries are grouped in one organization, and all Neuchâtel-Jura libraries in another.

2021-05-20 06:24 UTC, pronguen commented on content/post/sortie-de-la-v1.2.0.en.md
> +a dropdown menu on their account page. The patron does not need to switch
```suggestion
a dropdown menu on their account page. They don't need to switch
```

2021-05-20 06:24 UTC, pronguen commented on content/post/sortie-de-la-v1.2.0.md
> +## La traduction communautaire de RERO ILS
@iGormilhit En avez-vous discuté, avec Pascal? Il se trouve que les suggestions en l'état ne nous sont pas très utiles... Avec M. Gattlen, nous lui avons octroyé les droits d'écriture.
J'ai peur que ce billet encourage de nombreuses personnes à faire des suggestions que nous ne verrons pas forcément lors de la traduction.

2021-05-20 06:32 UTC, iGormilhit commented on content/post/sortie-de-la-v1.2.0.md
> +## La traduction communautaire de RERO ILS
@iGormilhit Oui on en a discuté, c'est spécifiquement à ma demande. Il ne s'agit pas des suggestions, mais de traductions qui sont effectivements ajoutées au code notamment en espagnol et en esperanto. Personne n'a besoin de droit d'écriture pour traduire sur les projets publics de weblate. Y avoir un compte suffit. Les droits sont pour éditer les paramètres du projet.

Le simple fait d'être sur hosted.weblate encourage des gens à traduire. Comme des gens le font, pourquoi ne pas remercier publiquement.

Par ailleurs, @mmo prépare un PR pour modifier le README de rero-ils dans le même sens. https://github.com/rero/rero-ils/pull/1891

2021-05-20 06:32 UTC, pronguen commented
**Ajouter la page en allemand**

---
title: "Release v1.2.0: Danke für die Übersetzungen!"
date: 2021-05-19
draft: false
tags: ["Mehrsprachigkeit", "release", "rero-ils"
---

Nach einem weiteren intensiven Sprint bei RERO+ und UCLouvain, bringt die Ankunft der Version `v1.2.0` ihren Anteil an neuen Funktionen und Korrekturen, um RERO ILS vor dem *Go-live* am 12. Juli zu stabilisieren. Die vollständigen Versionshinweise sind auf [GitHub](https://github.com/rero/rero-ils/blob/dev/RELEASE-NOTES.rst#v120) verfügbar. Dies ist die Gelegenheit für uns, den Community-Aspekt von RERO ILS mit den Übersetzungsprozessen des Systems hervorzuheben.

Die Folge des Textes is [auf Englisch](/en/sortie-de-la-v1.2.0/) oder [Französisch](/sortie-de-la-v1.2.0/) erhältlich.

2021-05-20 07:43 UTC, pronguen commented on content/post/sortie-de-la-v1.2.0.de.md
> +Versionshinweise sind auf GitHub verfügbar. Dies ist die Gelegenheit für uns,
```suggestion
Versionshinweise sind auf [GitHub](https://github.com/rero/rero-ils/blob/dev/RELEASE-NOTES.rst#v120) verfügbar. Dies ist die Gelegenheit für uns,
```

2021-05-20 07:44 UTC, pronguen commented on content/post/sortie-de-la-v1.2.0.md
> +(Neuchâtel-Jura). Celles-ci peuvent désormais consulter leurs données
```suggestion
(Neuchâtel-Jura). Elles peuvent désormais consulter leurs données
```

2021-05-20 08:33 UTC, merged