updates: foundation post
rero/rero21.ch pull request #57
Opened 2021-06-30 14:31 UTC by PascalRepond

Update à publier pour le 12 juillet (go-live), à relire, étoffer ou corriger.

2021-07-01 05:16 UTC, iGormilhit commented on content/post/la-fondation-rero-est-nee.md
> +Suite à la [nomination de Damian Elsig](https://www.admin.ch/gov/fr/accueil/documentation/communiques.msg-id-83356.html) à la tête de la Bibliothèque nationale Suisse, c'est Élisabeth Baume-Schneider
```suggestion
À la suite de la [nomination de Damian Elsig](https://www.admin.ch/gov/fr/accueil/documentation/communiques.msg-id-83356.html) à la tête de la Bibliothèque nationale Suisse, [Élisabeth Baume-Schneider](https://fr.wikipedia.org/wiki/%C3%89lisabeth_Baume-Schneider), conseillère aux États, devient la nouvelle présidente du Conseil de Fondation RERO+ dès le mois d'août 2021. Elle prend ses fonctions alors que le catalogue des bibliothèques clientes de RERO+ a été migré sur le nouveau système RERO ILS : [bib.rero.ch](https://bib.rero.ch/).
```

2021-07-01 06:28 UTC, pronguen reviewed
Voici mes commentaires. Je propose de valider le français, puis d'adapter ensuite les deux autres langues.

2021-07-01 06:28 UTC, pronguen commented on content/post/la-fondation-rero-est-nee.md
>      Par la suite, ce Conseil comptera entre 7 et 9 membres, couvrant plusieurs domaines de compétences et représentant d’autres parties prenantes telles que des partenaires stratégiques. Par ailleurs
```suggestion
    Au départ, chaque membre fondateur délègue un représentant au Conseil de fondation. Par la suite, ce principe ne devra pas forcément être respecté et le Conseil s'élargira pour compter 7 à 9 membres, couvrant plusieurs domaines de compétences et représentant d’autres parties prenantes telles que des partenaires stratégiques. Par ailleurs, des mécanismes de gouvernance spécifiques à RERO ILS et SONAR seront mis en place afin de donner un rôle actif à leur clientèle dans la conception des produits.
```

2021-07-01 06:28 UTC, pronguen commented on content/post/la-fondation-rero-est-nee.md
> +## Mise à jour - 12 juillet 2021
Ce titre n'est fait penser que nous n'avons pas modifié le reste de l'article. Je mettrais plutôt:

```suggestion
## Nouvelle présidente dès le 1er août: Elisabeth Baume-Schneider
```

2021-07-01 06:28 UTC, pronguen commented on content/post/la-fondation-rero-est-nee.md
> +Suite à la [nomination de Damian Elsig](https://www.admin.ch/gov/fr/accueil/documentation/communiques.msg-id-83356.html) à la tête de la Bibliothèque nationale Suisse, c'est Élisabeth Baume-Schneider
```suggestion
Peu après la création de la fondation, Damian Elsig a été [nominé à la tête de la Bibliothèque nationale Suisse](https://www.admin.ch/gov/fr/accueil/documentation/communiques.msg-id-83356.html). Une nouvelle personne intègrera le Conseil de fondation pour représenter le Canton du Valais.

Quant à la présidence, elle sera assurée dès le mois d'août 2021 par [Élisabeth Baume-Schneider](https://fr.wikipedia.org/wiki/%C3%89lisabeth_Baume-Schneider), conseillère aux États, alors que le catalogue des bibliothèques clientes de RERO+ a été migré sur le nouveau système RERO ILS : [bib.rero.ch](https://bib.rero.ch/).
```

Je me demandais s'il ne fallait pas rédiger une petite bio (1-2 phrases). On pourrait la lui faire valider la semaine prochaine. @mmo ?

Par ailleurs, je trouve cette phrase un peu hors contexte: *alors que le catalogue des bibliothèques clientes de RERO+ a été migré sur le nouveau système RERO ILS : [bib.rero.ch]*

2021-07-01 06:28 UTC, pronguen commented on content/post/la-fondation-rero-est-nee.md
>  C’est désormais officiel : l’identité de RERO évolue pour faire face à de nouveaux besoins dans un nouvel environnement bibliothéconomique. RERO devient RERO+, une fondation de droit privé et d’intér
Nous ne faisons nulle part mention des membres fondateurs, ce qui est déterminant.

```suggestion
C’est désormais officiel : l’identité de RERO évolue pour faire face à de nouveaux besoins dans un nouvel environnement bibliothéconomique. RERO devient RERO+, une fondation de droit privé et d’intérêt public formellement constituée le 29 avril 2021 par les cantons du Jura, de Neuchâtel et du Valais ainsi que la ville de Martigny. Cet événement représente le début d’une nouvelle aventure pour l'équipe RERO+ et ses partenaires.
```

2021-07-01 06:31 UTC, pronguen commented on content/post/la-fondation-rero-est-nee.md
>  C’est désormais officiel : l’identité de RERO évolue pour faire face à de nouveaux besoins dans un nouvel environnement bibliothéconomique. RERO devient RERO+, une fondation de droit privé et d’intér
```suggestion
*Mis à jour le 12 juillet 2021*

C’est désormais officiel : l’identité de RERO évolue pour faire face à de nouveaux besoins dans un nouvel environnement bibliothéconomique. RERO devient RERO+, une fondation de droit privé et d’intérêt public formellement constituée le 29 avril 2021. Cet événement représente le début d’une nouvelle aventure pour l'équipe RERO+ et ses partenaires.
```

2021-07-01 06:33 UTC, pronguen commented on content/post/la-fondation-rero-est-nee.md
>  C’est désormais officiel : l’identité de RERO évolue pour faire face à de nouveaux besoins dans un nouvel environnement bibliothéconomique. RERO devient RERO+, une fondation de droit privé et d’intér
@iGormilhit Idéalement on aurait un tag, comme pour la date de publication. Est-ce facilement faisable?

2021-07-01 07:26 UTC, iGormilhit commented on content/post/la-fondation-rero-est-nee.md
>  C’est désormais officiel : l’identité de RERO évolue pour faire face à de nouveaux besoins dans un nouvel environnement bibliothéconomique. RERO devient RERO+, une fondation de droit privé et d’intér
@pronguen 

C'est faisable. Il faut :

1. Ajouter une métadonnées de date : `lastmod`.
1. Configurer comment Hugo gère les dates, parce que par défaut il va remplacer la date de publication par la nouvelle date (cascade `date`, `publishdate`, `lastmod`). Alors que ce qu'on veut c'est avoir la date de publication *et* la date de la dernière modification.
1. Faire en sorte que le template ait la logique pour afficher ces données.

Je l'ai fait pour mon blog.

- https://framagit.org/iGormilhit/portfoligor/-/blob/dev/layouts/partials/post-info.html#L5 (la logique dans le template)
- https://framagit.org/iGormilhit/igor.milhit/-/blob/dev/config.toml#L18 (la conf pour les dates, chez moi ça se base sur les dates des commits)
- ce qui donne par exemple https://igor.milhit.ch/dis-kestekoute/ (ouvrir les informations sur le billet).

Je peux essayer de voir si j'arrive à faire quelque chose.

2021-07-01 09:36 UTC, iGormilhit commented on content/post/la-fondation-rero-est-nee.md
>  C’est désormais officiel : l’identité de RERO évolue pour faire face à de nouveaux besoins dans un nouvel environnement bibliothéconomique. RERO devient RERO+, une fondation de droit privé et d’intér
Voici ma proposition actuelle :

Pour la page d'accueil :
![ksnip_20210701-113427](https://user-images.githubusercontent.com/1557213/124102093-91e66880-da4f-11eb-80a3-d1aac96fca8d.png)

Pour le post lui-même :
![ksnip_20210701-113531](https://user-images.githubusercontent.com/1557213/124102238-b5111800-da4f-11eb-98e7-61d0f3c088d2.png)

Le texte est traduit. Il est en gras et dans le même bleu que les badges.

2021-07-08 13:41 UTC, mmo requested changes

2021-07-08 14:02 UTC, closed without merging